### ISSUE TITLE
Selectordie not displayed correctly

### ISSUE THREAD

**Issue by pshashi75** [vestman/Select-or-Die#33] opened 2015-04-17 06:48 UTC
We are using your plugin and for some time now the display of the control is not working correctly. 
I am attaching the screen shot for more explaination.
![img_1686](https://cloud.githubusercontent.com/assets/11989860/7197186/bea3f2de-e4fb-11e4-833d-575ddc9cb081.PNG)
![img_1685](https://cloud.githubusercontent.com/assets/11989860/7197185/bea290ba-e4fb-11e4-9514-98e835e43c0c.PNG)

Revert me if any further information required from my side to get this issue fixed.

Thanks.

**Comment by vestman** [comment] 2015-12-17 17:07
I took a look at the site and saw that you've ditched Select or Die (completely understandable).

Could it have been the case that you changed the `.sod_select.touch select` or had other styles overwriting the `select` selector? 

I'll close this issue since I'm not able to reproduce it. Feel free to open it again if you ever decide to give SoD another try.

**Closed as completed by vestman** 2015-12-17 17:07 UTC
