### ISSUE TITLE
Not functioning on IE 11.0.9600

### ISSUE THREAD

**Issue by ThomasGrolleau** [vestman/Select-or-Die#7] opened 2014-07-15 14:18 UTC
I'm soooooo disapointed because it's a very nice plugin but does'nt work on IE 11 on Win7, (not changing the item on  selection even if the "onChange" function seems to be triggered...) 
I hate IE...  I don't want to debug on IE sorry
But works fine on my Chrome and FF !

**Comment by ghost** [comment] 2014-07-16 19:39
I can confirm the same thing.  No IE 11 love on Win8 either.

**Comment by vestman** [comment] 2014-07-16 19:41
I'm on it!

P.S. Any chance one of you could check if #6 occurs for you to on Windows?

**Comment by ghost** [comment] 2014-07-16 19:43
#6 isn't an issue.  Looks perfect, just not keeping the selection.

**Comment by ThomasGrolleau** [comment] 2014-07-17 07:38
no #6 for me, it's working perfectly on my FF 30.0 on Win7

**Comment by thers** [comment] 2014-07-21 06:57
IE 10 on Win8 x64 is also affected, the only way to change seletion is focus on field using `tab` then `space` to open list then select item and hit `enter` button, everything else just won't work. And as i can see on site isn't the most recent version, because i see #4 bugs ;)

**Comment by robpataki** [comment] 2014-07-28 10:33
I can also confirm IE11/Win8 and IE10/Win7 has this issue. I just checked the selectordie (http://vst.mn/selectordie/) page after noticing the bug and none of the examples work on that page with IE :/

**Comment by stephenmcghee** [comment] 2014-07-30 14:22
Seems to be happening in all versions of IE.
After selecting an option, it reverts back to the original.

**Comment by robpataki** [comment] 2014-07-30 14:47
I looked into it the other day and I've found that the issue is lying in the `_private.optionClick` method. It seems that the jquery event delegation doesn't work in IE properly for some reason and the event target is always the first option.

**Comment by mlumbroso** [comment] 2014-07-30 15:05
Hi, 

here is what I see on your website with IE11.0.9600 and Win 8.

![bugie11](https://cloud.githubusercontent.com/assets/562562/3750974/db25bcf4-17fa-11e4-91cf-fd4168ca5165.jpg)

Thanks for the debug :-)

**Comment by cah4a** [comment] 2014-07-30 15:39
Hi!

I found that issue in `_private.focusSod`.
If detach this handler from $sod.focusin event, it work pretty good.

I think, we have here some IE bug. IE lose scope on `click` event, while using blur/focus methods.

**Comment by cah4a** [comment] 2014-07-30 16:41
Sorry, no IE bug here))

While clicking on some option, IE sends `focusin` event. `_private.focusSod` handler remove "open" class, so drop-down box disappears. 
IE not sends `click` event to hidden element, while `_private.focusSod` handler manually trigger `click` event on current active element.

https://github.com/cah4a/Select-or-Die/commit/2d5e057f99db6953c1558314fdb71c218e1e73e8
This hack do the trick.

**Comment by HandHugs** [comment] 2014-08-04 20:14
Also having this issue - IE 10 on Windows 8 not working at all - also tested IE 11 in windows 8.1, same result : can't select anything other than first option.

**Comment by janhocevar** [comment] 2014-08-05 12:36
I'm confirming that [@cah4a 2d5e957](https://github.com/cah4a/Select-or-Die/commit/2d5e057f99db6953c1558314fdb71c218e1e73e8) works.

**Comment by levsoroka** [comment] 2014-08-08 19:42
Yes fix from @cah4a works. 
@vestman you need to update your site, caz its broken in ie :)

**Comment by HandHugs** [comment] 2014-08-08 23:54
How do we make the change that @cah4a suggested? Can we make a fork that works in IE? Does this fix the issue with it not working in iOS, too??

**Comment by cah4a** [comment] 2014-08-09 16:26
@HandHugs you can simply use [that source](https://raw.githubusercontent.com/cah4a/Select-or-Die/2d5e057f99db6953c1558314fdb71c218e1e73e8/_src/selectordie.js).

In iOs it should fallback in system `select` behaviour:

![2014-08-09 19 22 23](https://cloud.githubusercontent.com/assets/694953/3866737/7cf98130-1fe1-11e4-95cd-b52a61294dc8.png) 
iPad

![2014-08-09 19 20 33](https://cloud.githubusercontent.com/assets/694953/3866736/7cf813cc-1fe1-11e4-8ebb-d62b82448234.png)
iPhone

**Comment by connorbond** [comment] 2014-09-10 15:59
Is this being actively worked on? I am also having the same issue on an ecommerce site, and simply removing for IE will not go down well with clients. 'Dropdown' appears, but the select is not updated

**Comment by ghost** [comment] 2014-09-10 16:20
There's already been several confirmations that cah4a@2d5e057 is the fix.  Thanks again @cah4a   

Read the comments before posting another "me too" or "fix it for me" post.  @vestman has been pretty silent on the pull requests so who knows if he's gonna merge anything.

**Comment by connorbond** [comment] 2014-09-10 16:28
I meant to ask whether it had been merged, I saw the comment but I am struggling to add this to my own copy. Sorry.

**Comment by vestman** [comment] 2014-09-16 23:56
Fixed and merged! Thanks for the help, @cah4a and everyone else!

**Closed as completed by vestman** 2014-09-16 23:56 UTC
